from typing import List, Optional, Dict
from pydantic import BaseModel, Field, ConfigDict, field_validator



class ProductCatalog(BaseModel):
    """
    Structured Pydantic model for AI-generated product catalog output.
    """
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "product_name": "Hand-painted Blue Terracotta Flower Vase",
                "category": "Home Decor",
                "description": "Exquisite hand-molded clay vase painted with traditional floral patterns using organic dyes.",
                "materials": ["Terracotta Clay", "Natural Pigments"],
                "craft_type": "Terracotta Pottery",
                "colors": ["Blue", "Terracotta Red", "White"],
                "tags": ["handmade", "vase", "terracotta", "pottery", "decor"],
                "confidence_score": 0.95
            }
        }
    )

    product_name: str = Field(
        ...,
        description="A concise, attractive product title suitable for e-commerce cataloging."
    )
    category: str = Field(
        ...,
        description="General category of the product (e.g., Home Decor, Apparel, Jewelry, Pottery, Woodcraft)."
    )
    description: str = Field(
        ...,
        description="A rich, buyer-friendly product description derived from visual features and artisan context."
    )
    materials: List[str] = Field(
        default_factory=list,
        description="List of primary raw materials used in crafting the item (e.g., Clay, Silk, Brass, Teak Wood)."
    )
    craft_type: str = Field(
        ...,
        description="Specific traditional craft technique or heritage style (e.g., Terracotta, Bandhani, Kantha, Madhubani)."
    )
    colors: List[str] = Field(
        default_factory=list,
        description="List of dominant colors identified in the product."
    )
    tags: List[str] = Field(
        default_factory=list,
        description="Keywords and search tags for product discovery."
    )
    confidence_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="AI confidence score for the catalog extraction quality between 0.0 and 1.0."
    )

    @field_validator("confidence_score")
    @classmethod
    def validate_confidence(cls, v: float) -> float:
        return round(float(v), 2)


class CatalogInput(BaseModel):
    """
    Input data model for product catalog generation.
    """
    image_bytes: bytes = Field(..., description="Raw bytes of the product image.")
    artisan_description: Optional[str] = Field(
        default=None,
        description="Optional text description or voice transcript provided by the artisan."
    )


class VoiceTranscriptionResponse(BaseModel):
    """
    Structured Pydantic response for Multilingual Speech-to-Text transcription.
    """
    transcribed_text: str = Field(
        ...,
        description="Transcribed text spoken by the artisan in original language or code-switched script."
    )
    detected_language: str = Field(
        ...,
        description="Detected language ISO code or name (e.g., kn-IN for Kannada, hi-IN for Hindi, en-US for English)."
    )
    confidence: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Confidence score between 0.0 and 1.0 if provided by STT engine, else None."
    )


class ErrorResponse(BaseModel):
    """
    Standardized error response format for API layer.
    """
    success: bool = Field(default=False)
    error: str = Field(..., description="Error message explanation.")
    status_code: int = Field(..., description="HTTP status code.")


class PricingInput(BaseModel):
    """
    Input schema for Smart Pricing Intelligence requests.
    """
    catalog: ProductCatalog = Field(..., description="Product catalog metadata generated by catalog AI module.")
    material_cost_inr: float = Field(default=0.0, ge=0.0, description="Raw material cost incurred by artisan in ₹ INR.")
    labor_hours: float = Field(default=1.0, ge=0.0, description="Labor hours spent by artisan in crafting item.")
    artisan_hourly_wage_inr: float = Field(default=100.0, ge=0.0, description="Desired or fair hourly wage rate in ₹ INR (default ₹100/hr).")
    packaging_shipping_cost_inr: float = Field(default=50.0, ge=0.0, description="Estimated packaging and logistics cost in ₹ INR.")
    market_tier: Optional[str] = Field(default="Fair Trade / Artisanal", description="Target market tier ('Mass Market', 'Fair Trade / Artisanal', 'Premium / Export').")


class PriceRange(BaseModel):
    """
    Price range boundaries.
    """
    min_price_inr: float = Field(..., description="Minimum fair selling price protecting artisan floor in ₹ INR.")
    recommended_price_inr: float = Field(..., description="Optimal target selling price in ₹ INR.")
    max_price_inr: float = Field(..., description="Upper bound price for premium/export channels in ₹ INR.")


class CostBreakdown(BaseModel):
    """
    Itemized cost and margin breakdown for financial transparency.
    """
    material_cost_inr: float = Field(..., description="Material cost in ₹ INR.")
    labor_cost_inr: float = Field(..., description="Labor cost (labor_hours * hourly_wage) in ₹ INR.")
    overhead_inr: float = Field(..., description="Packaging & shipping overhead in ₹ INR.")
    artisan_margin_inr: float = Field(..., description="Calculated artisan profit margin in ₹ INR.")
    cost_floor_inr: float = Field(..., description="Minimum viable cost floor price in ₹ INR.")


class PricingEstimateResponse(BaseModel):
    """
    Structured Pydantic response for Smart Pricing Intelligence engine.
    """
    recommended_price_inr: float = Field(..., description="Primary recommended selling price in ₹ INR.")
    price_range: PriceRange = Field(..., description="Minimum, recommended, and maximum price boundaries.")
    cost_breakdown: CostBreakdown = Field(..., description="Financial cost breakdown and artisan profit floor.")
    comparable_products_count: int = Field(..., description="Number of historical marketplace comps matched.")
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="Confidence score between 0.0 and 1.0.")
    pricing_explanation: str = Field(..., description="Human-readable rationale and pricing guidance for artisan.")


class MarketplaceSearchQuery(BaseModel):
    """
    Input schema for buyer marketplace search & recommendation engine.
    """
    query: Optional[str] = Field(default=None, description="Keyword search query (e.g. 'terracotta vase').")
    category: Optional[str] = Field(default=None, description="Target product category filter (e.g. 'Pottery').")
    craft_type: Optional[str] = Field(default=None, description="Specific traditional craft type filter (e.g. 'Terracotta').")
    location: Optional[str] = Field(default=None, description="Buyer location or artisan location filter (e.g. 'Karnataka').")
    price_min: Optional[float] = Field(default=None, ge=0.0, description="Minimum price filter in ₹ INR.")
    price_max: Optional[float] = Field(default=None, ge=0.0, description="Maximum price filter in ₹ INR.")


class ArtisanInfo(BaseModel):
    """
    Artisan metadata schema for buyer matching.
    """
    artisan_id: str = Field(..., description="Unique generic artisan ID (e.g. ART001).")
    artisan_name: str = Field(..., description="Artisan or collective display name.")
    location: str = Field(..., description="State/City location of the artisan (e.g. Channapatna, Karnataka).")


class MarketplaceProductItem(BaseModel):
    """
    Detailed product item returned in marketplace query.
    """
    product_id: str = Field(..., description="Unique product ID.")
    product_name: str = Field(..., description="Product title.")
    category: str = Field(..., description="Product category.")
    craft_type: str = Field(..., description="Craft technique.")
    materials: List[str] = Field(default_factory=list, description="Materials used.")
    description: str = Field(..., description="Product description.")
    price_inr: float = Field(..., description="Price in ₹ INR.")
    artisan: ArtisanInfo = Field(..., description="Artisan details.")
    tags: List[str] = Field(default_factory=list, description="Product tags.")


class MarketplaceMatchResult(BaseModel):
    """
    Single matched product result with relevance scoring and match reasons.
    """
    product: MarketplaceProductItem = Field(..., description="Matched product item details.")
    relevance_score: float = Field(..., ge=0.0, le=1.0, description="Overall matching relevance score between 0.0 and 1.0.")
    match_reasons: List[str] = Field(default_factory=list, description="Human-readable match explanation reasons.")


class MarketplaceSearchResponse(BaseModel):
    """
    Response schema for buyer marketplace search.
    """
    success: bool = Field(default=True)
    total_results: int = Field(..., description="Number of matching products found.")
    results: List[MarketplaceMatchResult] = Field(default_factory=list, description="Sorted list of matching products by relevance score.")


class MarketIntelligenceRequest(BaseModel):
    """
    Input schema for Market Intelligence analysis request.
    """
    location: Optional[str] = Field(default=None, description="Artisan state/region location (e.g. 'Karnataka').")
    craft_type: Optional[str] = Field(default=None, description="Artisan craft technique (e.g. 'Terracotta').")
    category: Optional[str] = Field(default=None, description="Product category (e.g. 'Pottery').")
    product_id: Optional[str] = Field(default=None, description="Optional specific product ID to analyze.")


class MarketIntelligenceResponse(BaseModel):
    """
    Response schema for Market Intelligence analysis.
    """
    success: bool = Field(default=True)
    demand_level: str = Field(..., description="Overall demand level ('Very High', 'High', 'Moderate', 'Emerging').")
    market_opportunity: str = Field(..., description="Market opportunity level ('Strong', 'Favorable', 'Growing', 'Niche').")
    trending_categories: List[str] = Field(default_factory=list, description="Top trending categories in the marketplace.")
    trending_crafts: List[str] = Field(default_factory=list, description="Top trending traditional craft types.")
    optimal_price_range_inr: Dict[str, float] = Field(default_factory=dict, description="Optimal price window ('min_price', 'max_price', 'median_price').")
    insights: List[str] = Field(default_factory=list, description="Actionable insights and business recommendations for the artisan.")
    search_count: int = Field(default=0, description="Total buyer search activity count.")
    view_count: int = Field(default=0, description="Total product view activity count.")
    customer_interest_pct: float = Field(default=0.0, description="Calculated buyer interest percentage.")
    growth_pct: float = Field(default=0.0, description="Calculated demand growth percentage.")


class GovernmentSchemeItem(BaseModel):
    """
    Verified Government Scheme data model.
    """
    scheme_id: str = Field(..., description="Unique scheme identifier (e.g. SCHEME-PM-VISHWAKARMA).")
    scheme_name: str = Field(..., description="Official scheme title.")
    ministry_department: str = Field(..., description="Administering Ministry or Department.")
    target_crafts: List[str] = Field(default_factory=list, description="Eligible craft types or 'All Traditional Crafts'.")
    target_locations: List[str] = Field(default_factory=list, description="Covered states or 'All India'.")
    eligible_business_statuses: List[str] = Field(default_factory=list, description="Eligible business types.")
    eligible_registration_statuses: List[str] = Field(default_factory=list, description="Accepted registration statuses.")
    benefit_description: str = Field(..., description="Explanation of financial, credit, toolkit, or training benefits.")
    eligibility_conditions: List[str] = Field(default_factory=list, description="Exact eligibility criteria constraints.")
    required_documents: List[str] = Field(default_factory=list, description="Mandatory application documents.")
    official_source_url: str = Field(..., description="Verified official government portal URL (.gov.in / .nic.in).")
    last_verified_date: str = Field(..., description="Last verification date string (YYYY-MM-DD).")
    verification_status: str = Field(default="Official Verified", description="Verification status.")


class SchemeMatchingRequest(BaseModel):
    """
    Input schema for Government Scheme Matching requests.
    """
    craft_type: str = Field(..., description="Artisan craft technique (e.g. 'Terracotta', 'Woodcarving').")
    location: str = Field(..., description="Artisan state/region location (e.g. 'Karnataka', 'Rajasthan').")
    business_status: Optional[str] = Field(default="Individual Artisan", description="Business type ('Individual Artisan', 'Self-Help Group (SHG)', 'Micro Enterprise').")
    registration_status: Optional[str] = Field(default="Unregistered / Informal", description="Registration status ('Pehchan Card Registered', 'Udyam Registered', 'Unregistered / Informal').")
    annual_income_inr: Optional[float] = Field(default=None, ge=0.0, description="Optional annual income in ₹ INR.")
    gender: Optional[str] = Field(default=None, description="Optional gender ('Female', 'Male', 'Other'). Evaluated ONLY when scheme mandates.")
    age: Optional[int] = Field(default=None, ge=0, le=120, description="Optional age in years. Evaluated ONLY when scheme mandates.")
    social_category: Optional[str] = Field(default=None, description="Optional social category ('General', 'SC', 'ST', 'OBC'). Evaluated ONLY when scheme mandates.")


class MatchedSchemeResult(BaseModel):
    """
    Matched scheme result item with match scoring and transparent criteria rationale.
    """
    scheme: GovernmentSchemeItem = Field(..., description="Government scheme details.")
    match_score: float = Field(..., ge=0.0, le=1.0, description="Match score between 0.0 and 1.0.")
    recommendation_reason: str = Field(..., description="Human-readable recommendation summary.")
    matched_criteria: List[str] = Field(default_factory=list, description="List of matched profile conditions.")
    unmet_criteria: List[str] = Field(default_factory=list, description="List of unmet prerequisite conditions.")


class SchemeMatchingResponse(BaseModel):
    """
    Response schema for Government Scheme Matching engine.
    """
    success: bool = Field(default=True)
    total_matched: int = Field(..., description="Number of matched government schemes.")
    results: List[MatchedSchemeResult] = Field(default_factory=list, description="Sorted list of matched schemes by match score.")




